import type { Job } from '@/types';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp India',
    location: 'Hyderabad, India',
    type: 'Full-time',
    experience: '5+ years',
    salary: '₹18-25 LPA',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    description: 'We are looking for a Senior Frontend Developer to lead our web application development. You will work with a talented team building scalable, user-centric applications.',
    postedDate: '2025-03-01',
  },
  {
    id: '2',
    title: 'Java Backend Engineer',
    company: 'FinTech Solutions',
    location: 'Bengaluru, India',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹12-18 LPA',
    skills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL'],
    description: 'Join our backend team to build robust financial services APIs. You will design and develop microservices handling millions of transactions daily.',
    postedDate: '2025-03-02',
  },
  {
    id: '3',
    title: 'Data Scientist',
    company: 'Analytics Pro',
    location: 'Remote',
    type: 'Full-time',
    experience: '4+ years',
    salary: '₹15-22 LPA',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL'],
    description: 'We need a Data Scientist to build predictive models and extract insights from large datasets. You will work closely with product and business teams.',
    postedDate: '2025-03-03',
  },
  {
    id: '4',
    title: 'Cloud DevOps Engineer',
    company: 'CloudNative Systems',
    location: 'Hyderabad, India',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹14-20 LPA',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    description: 'Manage our cloud infrastructure and CI/CD pipelines. You will automate deployments, monitor systems, and ensure high availability.',
    postedDate: '2025-03-04',
  },
  {
    id: '5',
    title: 'Full Stack Developer',
    company: 'StartupHub',
    location: 'Bengaluru, India',
    type: 'Full-time',
    experience: '2+ years',
    salary: '₹10-15 LPA',
    skills: ['React', 'Node.js', 'Express', 'MongoDB'],
    description: 'Build end-to-end features for our SaaS platform. You will work on both frontend and backend, from database design to UI implementation.',
    postedDate: '2025-03-05',
  },
  {
    id: '6',
    title: 'AI/ML Engineer',
    company: 'IntelliAI Labs',
    location: 'Remote',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹16-24 LPA',
    skills: ['Python', 'PyTorch', 'NLP', 'Computer Vision'],
    description: 'Develop and deploy machine learning models for our AI products. You will work on NLP, computer vision, and recommendation systems.',
    postedDate: '2025-03-06',
  },
  {
    id: '7',
    title: 'UI/UX Designer',
    company: 'Design Studio',
    location: 'Hyderabad, India',
    type: 'Full-time',
    experience: '2+ years',
    salary: '₹8-14 LPA',
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    description: 'Create beautiful, intuitive user experiences for web and mobile applications. You will work with product managers and developers.',
    postedDate: '2025-03-07',
  },
  {
    id: '8',
    title: 'Cybersecurity Analyst',
    company: 'SecureNet',
    location: 'Bengaluru, India',
    type: 'Full-time',
    experience: '3+ years',
    salary: '₹12-18 LPA',
    skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Python'],
    description: 'Protect our systems from security threats. You will monitor networks, conduct vulnerability assessments, and respond to incidents.',
    postedDate: '2025-03-08',
  },
];
