import type { StudyMaterial } from '@/types';

export const studyMaterials: StudyMaterial[] = [
  {
    id: 'web-dev',
    title: 'Web Development Notes',
    category: 'Web Development',
    description: 'Comprehensive notes covering HTML, CSS, JavaScript, React, and modern web frameworks.',
    icon: 'Globe',
    pages: 245,
    rating: 4.8,
    price: "free",
    originalPrice: 49.00,
  },
  {
    id: 'java',
    title: 'Java Notes Pack',
    category: 'Java',
    description: 'Complete Java notes from basics to advanced topics including Spring Boot and JDBC.',
    icon: 'Coffee',
    pages: 312,
    rating: 4.7,
    price: "free",
    originalPrice: 199.00,
  },
  {
    id: 'python',
    title: 'Profile Foundation',
    category: 'Python',
    description: 'Python fundamentals, OOP, data structures, and popular libraries like NumPy and Pandas.',
    icon: 'Code',
    pages: 198,
    rating: 4.9,
    price: "free",
    originalPrice: 129.00,
  },
  {
    id: 'data-science',
    title: 'Data Science Notes',
    category: 'Data Science',
    description: 'Statistics, machine learning, data visualization, and real-world project walkthroughs.',
    icon: 'BarChart3',
    pages: 287,
    rating: 4.8,
    price: "free",
    originalPrice: 219.00,
  },
  {
    id: 'ai-ml',
    title: 'AI/ML Notes',
    category: 'AI/ML',
    description: 'Deep learning, neural networks, NLP, and computer vision with practical examples.',
    icon: 'Brain',
    pages: 356,
    rating: 4.9,
    price: "free",
    originalPrice: 249.00,
  },
  {
    id: 'data-analytics',
    title: 'Data Analytics Notes',
    category: 'Data Analytics',
    description: 'Data cleaning, analysis techniques, SQL, Tableau, and business intelligence concepts.',
    icon: 'PieChart',
    pages: 224,
    rating: 4.6,
    price: "free",
    originalPrice: 139.00,
  },
  {
    id: 'dbms',
    title: 'Database Management Notes',
    category: 'Database',
    description: 'Relational databases, SQL, normalization, transactions, and NoSQL databases.',
    icon: 'Database',
    pages: 201,
    rating: 4.7,
    price: "free",
    originalPrice: 119.00,
  },
  {
    id: 'cloud-computing',
    title: 'Cloud Computing Notes',
    category: 'Cloud Computing',
    description: 'AWS, Azure, Google Cloud, containerization, and microservices architecture.',
    icon: 'Cloud',
    pages: 268,
    rating: 4.8,
    price: "free",
    originalPrice: 189.00,
  },
  {
    id: 'software-engineering',
    title: 'Software Engineering Notes',
    category: 'Software Engineering',
    description: 'SDLC, design patterns, testing, Agile methodology, and software architecture.',
    icon: 'Cpu',
    pages: 234,
    rating: 4.7,
    price: "free",
    originalPrice: 159.00,
  },
  {
    id: 'cyber-security',
    title: 'Cyber Security Notes',
    category: 'Cyber Security',
    description: 'Network security, cryptography, ethical hacking, and security best practices.',
    icon: 'Shield',
    pages: 279,
    rating: 4.9,
    price: "free",
    originalPrice: 229.00,
  },
];